// Codemap SessionStart injector — generated by "codemap install".
// Loaded via the "plugin" entry in opencode.json. Subscribes to
// session.created and injects the codemap guidance via the opencode SDK
// (session.prompt with noReply:true). The payload lives next to this file in
// the codemap data directory.

import { readFileSync, existsSync } from "node:fs"
import { fileURLToPath } from "node:url"

const DIR = fileURLToPath(new URL(".", import.meta.url))
const PROBE = "always use codemap MCP tools instead of Grep/Read"
const MARKER = "<!-- codemap:start -->"

export const CodemapInjectPlugin = async ({ client, directory }) => {
  return {
    event: async ({ event }) => {
      if (event.type !== "session.created") return
      const sessionID = event.properties?.info?.id
      if (!sessionID) return
      try {
        const section = loadSection(directory)
        if (!section) return
        await client.session.prompt({
          path: { id: sessionID },
          body: { noReply: true, parts: [{ type: "text", text: section }] },
        })
      } catch (err) {
        console.error("[codemap] inject failed:", err)
      }
    },
  }
}

function loadSection(directory) {
  if (fileContains(directory + "/AGENTS.md", PROBE) || fileContains(directory + "/AGENTS.md", MARKER)) {
    return ""
  }
  if (!existsSync(DIR + "graph.db")) return ""
  try {
    const payload = JSON.parse(readFileSync(DIR + "hook-payload.json", "utf8"))
    const section = payload?.hookSpecificOutput?.additionalContext
    if (typeof section === "string" && section.length > 0) return section
  } catch {}
  return ""
}

function fileContains(path, needle) {
  try {
    return readFileSync(path, "utf8").includes(needle)
  } catch {
    return false
  }
}
